### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'concatenate'

### ISSUE THREAD

**Issue by DX3906G** [liufanfanlff/RoboUniview#5]
Thanks for your excellent work! 

When I ran eval_ckpts.py, the following error occurs:
  traceback : Traceback (most recent call last):
    File "/home/gyq/miniconda3/envs/rounw/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
      return f(*args, **kwargs)
    File "robouniview/eval/eval.py", line 302, in main
      eval_one_epoch_calvin_ddp(
    File "/home/gyq/Programs/RoboUniview/robouniview/eval/eval_utils.py", line 712, in eval_one_epoch_calvin_ddp
      evaluate_policy_ddp(wrapped_model, env, 0, args.calvin_conf_path, eval_log_dir=eval_log_dir, debug=debug, reset=reset, diverse_inst=diverse_inst)
    File "/home/gyq/Programs/RoboUniview/robouniview/eval/eval_utils.py", line 517, in evaluate_policy_ddp
      result = evaluate_sequence(env, model, task_oracle, initial_state, eval_sequence, val_annotations, plans, debug, eval_log_dir, base_sequence_i+local_sequence_i, reset=reset, diverse_inst=diverse_inst)
    File "/home/gyq/Programs/RoboUniview/robouniview/eval/eval_utils.py", line 569, in evaluate_sequence
      success = rollout(env, model, task_checker, subtask, val_annotations, plans, debug, eval_log_dir, subtask_i, sequence_i,diverse_inst=diverse_inst)
    File "/home/gyq/Programs/RoboUniview/robouniview/eval/eval_utils.py", line 610, in rollout
      action = model.step(obs, lang_annotation,env, (len(planned_actions) == 0))
    File "/home/gyq/Programs/RoboUniview/robouniview/eval/eval_utils.py", line 381, in step
      action,_ = self.model(vision_x=image_x, lang_x=text_x, attention_mask=mask, vision_gripper = gripper, state_tensor = state,calib = calib, return_feature=True)
    File "/home/gyq/miniconda3/envs/rounw/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/gyq/miniconda3/envs/rounw/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
      output = self._run_ddp_forward(*inputs, **kwargs)
    File "/home/gyq/miniconda3/envs/rounw/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
      return module_to_run(*inputs[0], **kwargs[0])
    File "/home/gyq/miniconda3/envs/rounw/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/gyq/Programs/RoboUniview/robouniview/models/robouniview_mpt.py", line 261, in forward
      self._encode_multi_vision_UVformer_fusion(vision_x, vision_gripper, calib, state_tensor = state_tensor)
    File "/home/gyq/Programs/RoboUniview/robouniview/models/robouniview_mpt.py", line 392, in _encode_multi_vision_UVformer_fusion
      vision_x = torch.concatenate(vision_x, dim=2)
  AttributeError: module 'torch' has no attribute 'concatenate'

My torch version is 1.12.1+cu113

Could you please help me solve this error?

**Comment by liufanfanlff** [comment]
> Thanks for your excellent work!
> 
> When I ran eval_ckpts.py, the following error occurs: traceback : Traceback (most recent call last): File "/home/gyq/miniconda3/envs/rounw/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/**init**.py", line 345, in wrapper return f(*args, **kwargs) File "robouniview/eval/eval.py", line 302, in main eval_one_epoch_calvin_ddp( File "/home/gyq/Programs/RoboUniview/robouniview/eval/eval_utils.py", line 712, in eval_one_epoch_calvin_ddp evaluate_policy_ddp(wrapped_model, env, 0, args.calvin_conf_path, eval_log_dir=eval_log_dir, debug=debug, reset=reset, diverse_inst=diverse_inst) File "/home/gyq/Programs/RoboUniview/robouniview/eval/eval_utils.py", line 517, in evaluate_policy_ddp result = evaluate_sequence(env, model, task_oracle, initial_state, eval_sequence, val_annotations, plans, debug, eval_log_dir, base_sequence_i+local_sequence_i, reset=reset, diverse_inst=diverse_inst) File "/home/gyq/Programs/RoboUniview/robouniview/eval/eval_utils.py", line 569, in evaluate_sequence success = rollout(env, model, task_checker, subtask, val_annotations, plans, debug, eval_log_dir, subtask_i, sequence_i,diverse_inst=diverse_inst) File "/home/gyq/Programs/RoboUniview/robouniview/eval/eval_utils.py", line 610, in rollout action = model.step(obs, lang_annotation,env, (len(planned_actions) == 0)) File "/home/gyq/Programs/RoboUniview/robouniview/eval/eval_utils.py", line 381, in step action,_ = self.model(vision_x=image_x, lang_x=text_x, attention_mask=mask, vision_gripper = gripper, state_tensor = state,calib = calib, return_feature=True) File "/home/gyq/miniconda3/envs/rounw/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/gyq/miniconda3/envs/rounw/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward output = self._run_ddp_forward(*inputs, **kwargs) File "/home/gyq/miniconda3/envs/rounw/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward return module_to_run(*inputs[0], **kwargs[0]) File "/home/gyq/miniconda3/envs/rounw/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/gyq/Programs/RoboUniview/robouniview/models/robouniview_mpt.py", line 261, in forward self._encode_multi_vision_UVformer_fusion(vision_x, vision_gripper, calib, state_tensor = state_tensor) File "/home/gyq/Programs/RoboUniview/robouniview/models/robouniview_mpt.py", line 392, in _encode_multi_vision_UVformer_fusion vision_x = torch.concatenate(vision_x, dim=2) AttributeError: module 'torch' has no attribute 'concatenate'
> 
> My torch version is 1.12.1+cu113
> 
> Could you please help me solve this error?

You can upgrade the torch version to 2.4.1 or change torch.concatenate(vision_x, dim=2) to torch.cat(vision_x, dim=2).
